/* 389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

function findTheDifference(s: string, t: string): string {
    const map = new Map()

    //把string s中的所有字母都存入hashmap中
    for(let i = 0; i < s.length; i++){
        map.set(s[i], (map.get(s[i]) ?? 0) + 1);
    }

    //然后遍历String t里面的所有字母，找到多余的字母
    for(let i = 0; i < t.length; i++){
        if(map.has(t[i])){
            const freq = map.get(t[i]);
            if(freq > 1){ //这个字母还有剩余的
                map.set(t[i], freq - 1);
            } else { //这个字母只出现一次，从hashmap中删除这个字母
                map.delete(t[i]); 
            }
        } else{ //找到了多余的字母，直接输出
            return t[i];
        }
    }
};
